alphagov/spotlight

app/server/templates/page-components/report_a_problem.html

https://www.agileplannerapp.com/boards/105200/cards/5814
Addresses line 26 of the spreadsheet of copy changes for that ticket.
Part of a group of 4 pull requests for the same content:
- https://github.com/alphagov/spotlight/pull/880
- https://github.com/alphagov/feedback/pull/144
- https://github.com/alphagov/performanceplatform-selfserve/pull/1
- https://github.com/alphagov/static/pull/517

Personal information warning feedback copy change

---

app/client/controller_map.js
app/client/modules/section.js
app/client/views/visualisations/section.js
app/common/modules/section.js
app/extensions/controllers/module.js
app/server/controller_map.js
app/server/modules/section.js
app/server/templates/modules/section.html
app/server/views/modules/section.js
app/stagecraft_api_client.js
app/support/stagecraft_stub/responses/carers-allowance-sectioned.json
schema/module.json
schema/modules/section.json
spec/server-pure/modules/spec.section.js
spec/server-pure/views/spec.section.js
spec/shared/spec.stagecraft_api_client.js
styles/common/sections.scss
styles/common/tabs.scss
styles/index.scss

This cannot be merged until both alphagov/stagecraft#273 and alphagov/performanceplatform-admin#75 are merged.

Spotlight has sections

---

app/server/templates/page-components/footer_links.html

https://www.agileplannerapp.com/boards/105200/cards/8053

Change GDS footer link

---

app/server/controllers/services.js
app/support/stagecraft_stub/responses/transaction-data.json
spec/server-pure/controllers/spec.services.js

Fixup data stup for the tests.

Fixup tests for services controller.

---

app/server/templates/homepage.html

Change h1 to just *Performance*
Update lead paragraph to current proposition statement
Remove Get a dashboard aside

Small update to homepage

---

app/server/templates/dashboard.html
app/server/templates/services.html
styles/common/dashboard-footer.scss
styles/common/header.scss
styles/common/layout.scss
styles/typography.scss

Reverts alphagov/spotlight#892

Revert "Iterate dashboard template"

---

app/server/views/services.js

To show the KPIs/list view better.

Use an example with more data on /services

---

CONTRIBUTING.md

Opening for visibility. Not sure whether this is a good idea or not, but
would like to have a discussion about it.

Add suggestion for images in pull requests

---

app/client/views/services.js
app/extensions/views/table.js
app/server/templates/services.html
spec/shared/extensions/views/spec.table.js
styles/common/responsive_content.scss
styles/common/table.scss
styles/index.scss

Enable sort function on mobile screens

---

app/client/views/services.js
app/client/views/table.js
app/extensions/views/table.js
app/server/templates/services.html
spec/client/views/spec.table.js
spec/shared/extensions/views/spec.table.js
styles/common/responsive_content.scss
styles/common/table.scss
styles/index.scss

This restricts to the services page only, when the table sort is changed it will be saved to the URL.

Table sort - only store in URL if config set

---

app/extensions/views/table.js
styles/common/table.scss

- fix for table heading alignment - align heading to match the content
- force long cell contents eg. URLs to break

Table formatting

---

app/server/controllers/web-traffic.js
app/server/templates/web-traffic.html
app/server/views/services.js
app/server/views/web-traffic.js
spec/server-pure/controllers/spec.web-traffic.js
spec/server-pure/views/spec.web-traffic.js

Story - https://www.agileplannerapp.com/boards/15088/cards/9327
Simple, sortable list with keyword filter.

Add web traffic page

---

.travis.yml

Interesting to track alternative runtimes.

Try running builds in io.js too

---

app/server/controllers/services.js
styles/common/layout.scss

- use Prison visits as one of the showcase dashboards
- full width banner - ensure full width below 1024px viewport width

Home page changes

---

app/server/controllers/web-traffic.js
app/server/templates/homepage.html
app/server/templates/web-traffic.html
app/server/views/homepage.js
spec/server-pure/views/spec.homepage.js
styles/common/icons.scss
styles/common/layout.scss
styles/pages/homepage.scss

- icons for top 5 lists get smaller on smaller screens
- vertical spacing reduces on smaller screens

Homepage - responsive improvements

---

.travis.yml

Working around transient failures. We should not be in this mode for
long.

Remove cheapseats from travis build

---

app/client/views/graph/linelabel.js
app/server/templates/modules/completion.html
app/server/templates/modules/user-satisfaction-graph.html
app/server/templates/modules/visitors-realtime.html
spec/client/views/views/graph/spec.linelabel.js
spec/client/views/views/graph/spec.stacked-linelabel.js
styles/common/graph.scss
styles/common/grouped_timeseries.scss
styles/common/impact_number.scss
styles/common/visitors_realtime.scss

Changes and grabs to show differences are here - 
https://www.agileplannerapp.com/boards/15088/cards/8678
Mostly at narrow viewport

Graphs - responsive styling changes

---

app/client/views/graph/linelabel.js
spec/client/views/views/graph/spec.linelabel.js
styles/common/graph.scss

Feedback from the product review of this story - https://www.agileplannerapp.com/boards/15088/cards/8678

Graph css fixes

---

app/server/templates/dashboard.html

Point to production server until relative URL for each environment is provided

Use absolute path for big screen link

---

package.json

To include fix for mis-spelt 'February' in tests

Bump cheapseats version

---

.gitignore
app/server/templates/homepage.html
tests/functional/home-page.js
tests/functional/services.js
tests/functional/web-traffic.js

Fix functional tests to use new API data (dashboard names changed etc)
Add new functional tests for web traffic and home page

Functional tests

---

.travis.yml

http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Use sudo false where possible to speed up builds in travis

---

app/server/views/dashboard.js
spec/server-pure/views/spec.dashboard.js

Add big screen links to all dashboards that have supporting modules not just transaction and high volume.
Update tests to reflect this.

Add support for table modules.

---

app/extensions/controllers/controller.js
app/process_request.js
app/server/controllers/error.js
app/server/controllers/services.js
spec/server-pure/controllers/spec.services.js
spec/server-pure/spec.process_request.js

This reverts commit 663ae0229ef206b08fe93cb587e748386f584b07, reversing
changes made to a2418b0111d34abc4eabcfde779efb38b6d810b5.
The pull request should not have been merged.

Revert "Merge pull request #971 from alphagov/feature/error-caching"

---

app/server/templates/homepage.html

Copy changes

---

app/server/templates/homepage.html

Still need to look at the big dashboard links...

Edited body copy

---

app/appBuilder.js
app/extensions/controllers/controller.js
app/extensions/models/data_source.js
app/page_config.js
config/config.development.json
spec/server-pure/spec.environment_config.js
spec/server-pure/spec.process_request.js

Also update the log file location and log some more detail when there is a problem
fetching data

Split internal and external requests to backdrop

---

app/extensions/collections/collection.js
app/extensions/models/data_source.js
app/server/views/module.js
spec/shared/extensions/models/spec.data_source.js

Because the json link is generated server side, it was picking up the
internal only backdrop url which would not work. Change this to request
an external url on the collection.

Fix json data link

---

app/extensions/collections/collection.js
app/extensions/controllers/controller.js
app/extensions/mixins/performance.js
app/process_request.js
spec/server-pure/spec.process_request.js

Adding some performance measurement for the data acquisition and rendering of dashboards and constituent modules.

Request breakdown timing

---

app/server/templates/homepage.html
styles/elements/_layout.scss
styles/pages/homepage.scss

This reverts commit 27c42fda1158c03d3eac9db64048df1aed529353. Re-instating a commit reverted by accident in previous pull request.

Revert "Revert "Change 'get a dashboard' CTA""

---

Jenkinsfile

This just runs the existing jenkins.sh in the build phase.

Add Jenkinsfile for new CI

---

package.json

Update cheapseats dependency as this is also used by CI

Update the dev dependency commitish for cheapseats

---

app/server/templates/module.html
app/server/views/module.js

Depends on [backdrop/pull/470](https://github.com/alphagov/backdrop/pull/470)

Added CSV download

---

app/client/modules/tab.js

Tabbed views were missing Collection and were not rendering same as plain content views.

Fix tabbed views

---

app/client/views/json-summary.js
package.json
spec/client/views/spec.json-summary.js

Added missing csv url to json summary

Added csv url

---

app/server/templates/homepage.html
app/server/templates/page-components/navigation.html
styles/elements/_layout.scss

Removed `web traffic dashboards` from navigation.

Remove navigation item

---

app/server/templates/page-components/survey.html
app/server/views/govuk.js
styles/common/header.scss
styles/common/survey.scss
styles/index.scss

It's been talked about for days, but finally it's here! 
⚡️ ⚡️  [The link to a user research sign-up form!](https://trello.com/c/CG0t30Mr/216-ur-form-on-the-performance-platform-to-recruit-more-annas) ⚡️ ⚡️ 
All our users who want to be recruited won't stand a chance.
[The actual form is here](https://goo.gl/forms/Q5QGw0tmdj93TyUh2), for those who want to have a look at it. The design is based off of the  survey link at the top of the [Service Manual](https://www.gov.uk/service-manual), and the words come from [this document](https://docs.google.com/document/d/1ilvAD4X4k1c4SDNUicyUBPMWLNK7hetZbqEefiXO5AU/edit). The form itself can be edited on the fly so it's not tightly coupled to this pull request, but it seems like it's useful context. (Additionally, users who are monitoring our github …

Add user research survey link to Performance Platform

---

manifest.production.yml

Rename to use shared `logit-ssl-drain`

update logit service name

---

manifest.production.yml
manifest.staging.yml
package.json

- It's the new Ubuntu Bionic instead of Trusty.

Upgrade PaaS stack to cflinuxfs3

---

manifest.production.yml
manifest.staging.yml
package.json

To deploy to staging, we need to push stuff to this branch. Will do prod if this goes well 👍

Release master to staging

---

manifest.production.yml
manifest.staging.yml
package.json

Release master to production

---

README.md
app/appBuilder.js
app/server/controllers/accessibility.js
app/server/templates/accessibility.html
app/server/templates/page-components/footer_links.html
app/server/views/accessibility.js

* adds a new html view to render the accessibility content
* link to the page from the footer links
* Deployment is unusual here and based on merging into `staging` and `production` branches

Add accessibility statement for performance platform
