- app/server/views/dashboard.js
- spec/server-pure/views/spec.dashboard.js
Previously we were showing links to big screen view even if there were
no supported modules to display. This commit will check whether the
array of modules includes any that are supported and if there are then
allow the link to be displayed.
> Only show big screen link if supported

- app/common/views/visualisations/volumetrics/target.js
- spec/client/views/visualisations/volumetrics/spec.target.js
This ensures the module doesn't blow up when the collection is empty.
> Render (no data) for missing data in applications module.

- spec/server-pure/helpers.js
If you run this command at moment it will fail as there's no global logger defined.
It works if you run the main jasmine_node as the helpers for ```legacy``` add it to the global.
This adds it to the global for server so you can now just run the server tests only and be happy.
> Fix ```grunt jasmine_node:server``` command

- app/server/templates/dashboard.html
- app/server/templates/services.html
- styles/common/dashboard-footer.scss
- styles/common/header.scss
- styles/common/layout.scss
- styles/typography.scss
Refactor to use govuk_frontend_toolkit _grid_layout
Make dashboard small-print font-size: 16px (ie smaller)
Add service description to the top of the dashboard, remove tagline (it didn't add anything)
> Iterate dashboard template

- .gitignore
Without a leading / git will ignore all files/folders named dashboard in the
repo
> gitignore /dashboards folder at root only

- styles/common/graph.scss
The labels in the legend for graphs like https://www.gov.uk/performance/register-to-vote/registrations-by-age-group cause a slightly nasty overlap because a line break appears on hover.
Setting the right value at 0 allows the absolutely positioned labels to fill the full width of the parent container, and so prevents the line breaks appearing when the font-face is changed to bold.
This fixes the bug I reported yesterday. I thought you guys might appreciate it since I imagine you're getting a lot of hits lately.
> Fix line breaks in legend labels on hover

- README.md
- app/server/views/modules/grouped_timeseries.js
Start a 'contributing' section in readme. Could also include [Jabley's suggestion](https://github.com/alphagov/spotlight/pull/902) about adding explanatory images to PRs
> Readme / lint

- app/common/collections/services.js
- spec/shared/common/collections/spec.services.js
Test case - /performance/services?filter=stud&sortby=digital_takeup&sortorder=descending
Before - Digital takeup was 100%
After - Digital takeup was 96.7%
> Fix - weighted averages now computed to correct number of decimal places

- app/server/templates/dashboard.html
- app/server/templates/module.html
- styles/common/header.scss
Takes up less vertical space – get to the content quicker
Still red and noticeable
> Slightly smaller prototype message

- .travis.yml
Reverts alphagov/spotlight#913
This was a bad idea. All builds fail now.
> Revert "Try running builds in io.js too"

- app/client/views/table.js
- spec/client/views/spec.table.js
Fixes a JS error in /performance/govuk-verify
> Don't rely on an X axis being supplied for a table module

- app/server/templates/homepage.html
We have referred to services throughout our homepage. This was the only reference where "transactional services" remained. This is to remove that and gain consistency across the homepage.
> Remove the word "transactional" from page link

- app/client/views/services-kpi.js
- app/client/views/table.js
- app/extensions/views/table.js
- spec/client/views/spec.table.js
- spec/shared/extensions/views/spec.table.js
Accessibility recommendations from Leonie Watson - 
1 - Unsorted state.
This is a minor nit. When a column is unsorted the hidden “Click to sort” information is helpful. Once the column has been sorted it isn’t needed though because screen readers will take the sorted state from the aria-sorted attribute. 
Recommend removing the hidden text once a column has been sorted.
2 - Link function..
When a link such as “94 services out of 115” is activated, it causes the table to be sorted and for the table to be scrolled into view. Keyboard focus remains on the link though.
Recommend moving keyboard focus to the table when one of these links is activated.
In terms of the live region announcement, keeping it short is a good idea. Your suggestion to indicate what/where something has changed seems …
> Services page accessibility

- app/client/views/services.js
Headers should stick as you scroll the table body, in the same way as all other tables on the site.
> Restore sticky headers to services table

- Procfile
- package.json
Heroku crashes due to the digest not being published.
This adds a grunt build before it starts the app.
> Heroku deploy

- package.json
Reverts alphagov/spotlight#927
> Revert "Bump Cheapseats (fix for dashboard JSON download errors)"

- package.json
Update cheapseats to latest version.
> Bump Cheapseats (fix for dashboard JSON download errors)

- jenkins.sh
ci-new is currently failing frequently and blocking deploys. Until we
can make it more robust we will run fewer cheapseats tests and test more
manually
> Run fewer cheapseats tests in ci-new

- app/extensions/views/view.js
This is required for things like bar_chart_with_number to format a period of a year if you specify one.
FTAO @mharrington
> Add year formatting for axes-period.

- app/stagecraft_api_client.js
This is to help tracking down 404 errors in spotlight that we suspect
are related to stagecraft not responding correctly.
> Log status / error text of stagecraft request

- app/server/templates/modules/bar_chart_with_number.html
"Bar Chart with Number" widget didn't have fallback URLs in the template so on IE8 etc. only the number, not the bar chart is displayed.
This version of the template with the fallback URL also uses a selector to exclude the Number region so it isn't displayed twice.
Before:
After:
> Include fallback URLs in "Bar Chart with Number" widget template

- app/client/views/graph/graph.js
- app/client/views/graph/linelabel.js
- app/client/views/visualisations/grouped-graph/grouped-graph.js
- app/client/views/visualisations/grouped_timeseries.js
- app/common/modules/grouped_timeseries.js
- spec/client/views/views/graph/spec.linelabel.js
- spec/client/views/views/graph/spec.stacked-linelabel.js
https://www.agileplannerapp.com/boards/15088/cards/9374
It can be disabled by setting `show-total-label` to false in the dashboard.
> Ability to turn off total label in grouped timeseries

- app/client/views/graph/linelabel.js
- spec/client/views/views/graph/spec.linelabel.js
- styles/common/graph.scss
- Fix bug in grouped time series graph legends where, at narrow viewports only, you can hover over one label and a different one highlights.
- Fix issue caused by [this commit](https://github.com/alphagov/spotlight/commit/56ecbc9e8f90acc9eba2467fcb1eaffee2e2d025) where legend labels on [this dashboard](/performance/student-finance-england-full-time-study-applications/volumetrics) were using a too-large font size.
- Legend labels - reduce likelihood of wrapping
> Graph css fixes

- app/client/views/graph/linelabel.js
- spec/client/views/views/graph/spec.linelabel.js
When format is specified as `format: 'currency'` shorthand the property is not used.
This fix puts it in line with how formatting is done elsewhere on spotlight.
If format is specified like so:
`format: 'percent'`
Spotlight mixes it into the format defaults.
If it's:
```
format: {
type: 'percent'
}
```
It will also mix that into the defaults.
Added tests around this as there were none.
> Fix formatOptions problems.

- .travis.yml
- Gruntfile.js
- README.md
- jenkins.sh
- package.json
For a balance of good coverage and speed for CI, add a flag to allow Cheapseats to be run with a small subset of dashboards. 
- command line flag for cheapseats (--quickrun). Updated travis and jenkins scripts to use this.
- new grunt task - cheapseats_quick_run
> Cheapseats - allow subset of dashboards to be run

- styles/common/bar_chart_with_number.scss
By bumping font size down slightly
> Bar graph labels - avoid overlapping

- styles/common/table.scss
Make tables scrollable on wide viewport only
Always show scroll handle on mac / webkit
> Table scroll behaviour

- app/appBuilder.js
- app/page_config.js
- app/server/templates/dashboard.html
- config/config.development.json
- spec/server/spec.page_config.js
Use config from [pp-deployment](https://github.gds/gds/pp-deployment/pull/458) to set root URL for big screen link from dashboards.
> Take big screen root URL from config

- app/client/views/visualisations/grouped-graph/line-graph.js
So that modules with many low values have a sensible Y axis range.
Story - https://www.pivotaltracker.com/n/projects/911872/stories/89863070
> For grouped line graph, set min Y value to zero

- app/server/views/dashboard.js
- spec/server-pure/views/spec.dashboard.js
Add a link for bigscreen when only grouped_timeseries modules are on a dashboard
> Show the bigscreen link for grouped_timseries dashboards

- Gruntfile.js
- app/client/views/services-kpi.js
- app/client/views/services.js
- app/client/views/table.js
- spec/client/common/views/spec.services.js
- spec/client/views/spec.services-kpi.js
- spec/client/views/spec.table.js
Analytics events sent for the following user actions:
- Filter list of services by text or department dropdown
- Sort table by column headings
- Click links below summary figures to sort table
All will appear under the events category 'ppServices'
> Services page analytics events

- app/server/controllers/services.js
- spec/server-pure/controllers/spec.services.js
There are 4 predefined 'showcase' services to display at the top of the home page - 'prison-visits', 'book-practical-driving-test', 'carers-allowance', 'renew-patent'
There wasn't a proper check that each of these was present in the list of dashboards from the API, before adding to a list for rendering. This has now been corrected and error logging improved.
> Homepage - check if showcase service is found before adding

- app/server/controllers/dashboard.js
- app/server/templates/dashboard.html
- app/server/views/dashboards/other.js
- spec/server-pure/controllers/spec.dashboard.js
- spec/server-pure/views/spec.dashboard.js
New template type for 'Other' dashboards.
- description duplicated to section below main heading (replacing tagline)
- footer displayed by default
also -
- link to service only shown if URL supplied from API (bug fix for all dashboard templates)
> Dashboard template for 'other' dashboards

- app/client/controllers/services.js
To prevent the view always rendering with the full set of models.
> Fix - update the services filter before rendering

- app/server/templates/page-components/footer_links.html
- Research shows users think clicking the "Cymraeg" link will take
them to a translated version of the page they are on, rather than a
specific list of services GOV.UK has translated into Welsh. The
phrase "Rhestr o Wasanaethau Cymraeg" better describes the nature of
the page users are taken to.
- Originally changed this in https://github.com/alphagov/static/pull/578
and am now updating everything that contains our footer without
pulling in `static`.
> Change the text of the "Cymraeg" link in the footer

- app/client/views/date-picker.js
- spec/client/common/views/spec.date-picker.js
Our collectors run once a day so daily data is always one day behind.
If you select the current month then we need to roll back a day from (now) so that we don't show no data for the current month...
> Fixes no-data when selecting current month.

- app/server/templates/dashboard.html
- app/server/templates/services.html
- package.json
Changed the copy in the list headers to:
Departments to Ministerial departments
Agencies to Other departments & public bodies
Also changed the footer of the dashboards:
Department to Ministerial department
Agency to Other department or public body
> The drop-down lists to select services by department are inconsistent with those on the rest of gov.uk

- app/extensions/controllers/controller.js
- app/process_request.js
- app/server/controllers/error.js
- app/server/controllers/services.js
- spec/server-pure/controllers/spec.services.js
- spec/server-pure/spec.process_request.js
If an attempt to render a dashboard fails, we should not cache the
response for the normal period. Instead, allow a small window to allow
the system to recover if it’s under load.
> Specific caching directives for error HTML

- app/process_request.js
- spec/server-pure/spec.process_request.js
Before we would always pass all traffic through to stagecraft and let that work out if a url was valid.
We now ensure that urls like ```/performance/carers-allowance&quot``` do not get passed through to stagecraft and instead just 404 like they should.
> Ensure we 404 on a bad query param request.

- app/common/modules/grouped_timeseries.js
- spec/shared/common/collections/spec.grouped_timeseries.js
- spec/shared/common/collections/spec.grouped_timeshift.js
This is not used.
group_by has replaced this functionality.
> Removed category from grouped_timeseries.

- Gruntfile.js
- app/client/analytics.js
- package.json
__To be deployed 2 June.__
On 2 June we plan to deprecate Google Analytics classic on GOV.UK, from then on we will only use Universal analytics. Google Analytics classic data collection techniques are being deprecated by Google. We should no longer support classic and new tracking should use only Universal.
Following on from https://github.com/alphagov/govuk_frontend_toolkit/pull/194
Part of https://www.pivotaltracker.com/story/show/93002726
* Bump govuk_frontend_toolkit to pull in latest analytics
* Remove references to classic tracker
* Remove classic specific arguments (eg custom variable name and scope)
* Update references of `GOVUK.Tracker` to `GOVUK.Analytics`
(Changes made in https://github.com/alphagov/spotlight/pull/953 used as a reference)
cc @easternbloc
> Remove Google Analytics classic

- app/client/views/summary-figure.js
- spec/client/views/spec.summary-figure.js
This is to ensure we don't let people inject html into our results pages.
It's not a big XSS but it's still not very nice that this is currently happening.
TESTS!
> Use _ templates for summary figure pages.

- app/extensions/collections/collection.js
- spec/shared/extensions/collections/spec.collection.js
This is because the end period can be in outside the current date period (therefore we shouldn't show it)
Added tests to prove how defined works
We assume that if there is no end_at we're not dealing with a period... it's just a value at that time (slight hack but seems to be the least damaging to the code base.)
We filter the collection at parse() to ensure that the collection has no models from the future (should be done in backdrop).
> Ensure that models with a _end_at can't be from the future!

- app/client/views/graph/yaxis.js
- app/client/views/visualisations/bar-chart/bar-chart.js
- spec/client/views/views/graph/spec.yaxis.js
We currently only support percentage formatting in a  grouped timeseries using the setting "one-hundred-percent" this PR allows you to just plot lots of percentages on a graph (multuple series won't add up to 100% so it could be confusing to the user).
This is something that @cliffshepp requested so anyone thinking hmmm not sure this is a good idea should talk to him!
:zap::zap::zap:
> Allow the y axis of a graph to just be a percentage

- app/server/templates/page-components/footer_top.html
This link still goes to /visas-immigration which redirects 
to /browse/visas-immigration.
This breaks the In-Page Analytics view in Google Analytics,
because the next page tracked doesn't match the link.
Updated to go directly to /browse/visas-immigration.
> Update visa-immigration link

- app/client/views/services-kpi.js
- app/common/collections/services.js
- app/server/views/services.js
- spec/client/views/spec.services-kpi.js
- spec/server-pure/views/spec.services.js
if the weighted average of something is 0 (sometimes happens with
filtered services pages) then we currently do not display it. Not 100%
about whether we need to change both of these if statements I should
admit but this does this trick.
This uncovered a further bug:
Previously we would always initialize the aggregrates for the services
page with 0s, however if no data was found for an service page aggregate
kpi then this would show up as 0 on the page itself in the case of
number of transactions and total cost because of the way these avoid the weighted_average logic.
This changes the logic so that if no kpi is yet defined we first check
there is actually volume information before adding it to aggregates.
This has the problem that even if there is a value it will not be
counted in the …
> Fix ignore 0s in service page totals

- app/common/collections/services.js
- spec/server-pure/views/spec.services.js
Previously we only added 0s to the weighting for the first value. This
was wrong and foolish of me.
Things now look like this.
> Fix 0 handling beyond the first value in the aggregate

- app/server/templates/page-components/footer_top.html
Hi team!
This adds the link to the new "Childcare and parenting" browse page in the footer.
See PR on static for previous art: https://github.com/alphagov/static/pull/622
> Add Childcare and parenting link in footer

- app/client/views/json-summary.js
- app/client/views/module.js
- app/server/templates/module.html
- spec/client/views/spec.json-summary.js
Update link to json summary in the client view based on selection in date picker.  Keeping
old json link based on server side as a fallback for when javascript isn't enabled.
> Fix link to json summary not updating when dates are changed.

- Gruntfile.js
The jasmine_node tests were failing when trying to require the jquery node module (required in spec/helpers.js). Deep in its dependency tree is a module called json-schema which has a file called validate.js. This file checks for the existence of a function called 'define' in the global namespace and if it doesn't exist it creates one. The Gruntfile.js file was creating a function of this name in order to read in the application settings file (app/config.js) and its existence was causing validate.js to fail.
The problem has been fixed by removing the 'define' function from the global namespace after it has served its purpose in Gruntfile.js.
Note - this error has only recently started to occur. I'm unable to explain why the tests were not breaking before.
> Fix broken Jasmine tests

- app/client/views/services.js
- app/extensions/views/table.js
- app/server/controllers/services.js
- app/server/controllers/simple-dashboard-list.js
- app/server/controllers/tools.js
- app/server/templates/homepage.html
- app/server/templates/services.html
- app/server/views/homepage.js
- spec/client/common/views/spec.services.js
- spec/server-pure/views/spec.homepage.js
- spec/server-pure/views/spec.services.js
- spec/shared/extensions/views/spec.table.js
- styles/common/kpi.scss
- styles/typography.scss
- tests/functional/home-page.js
The data about services on the /performance home page and the services page can be incorrect and misleading, and doesn't match the data on the individual dashboard. 
To remove some the confusion, the performance homepage has been changed into a navigation page and the descriptions for each KPI has been updated. 
Also, the aggregate KPI data has been removed from the services page.
The only place service performance data should be displayed now is on the individual dashboards
Pivotal: https://www.pivotaltracker.com/story/show/111592970
Pivotal: https://www.pivotaltracker.com/story/show/111591258
> Remove data from home page and services page

- app/server/templates/page-components/footer_links.html
- It was advised that we include this link prominently in the (rare)
event of legal action against us for something on the site.
- Related to https://github.com/alphagov/static/pull/714.
> Add a link to GOV.UK's Terms and Conditions to the footer

- app/extensions/views/table.js
- app/server/controllers/services.js
- app/server/controllers/simple-dashboard-list.js
- app/server/templates/homepage.html
- spec/shared/extensions/views/spec.table.js
- tests/functional/services.js
All of the graphs on the dashboards are underpinned by a table.
If javascript is turned off the table is displayed instead of the graph.
The hack added to add a department name had broken this feature. The
code that renders tables is shared across spotlight. When the department
name was added to the table rendering code, it was also added behind the
scenes to every graph. The graphs still rendered correctly, but when
javascript was turned off, the table failed to render.
Added a  fix to allow the x axis of the graph/table to accept a list or
a single value. This is because whilst some of the config for the x and
y axes is held in spotlight, the majority of it is held in the module
config in stagecraft and can only be edited via the admin app.
Also add integration tests for the services …
> Fix tables

- styles/pages/servicespage.scss
The CSS positioning of the Completed transactions per year column title on the Services page was not responding well when table data is filtered. An alternative CSS positioning approach fixes this.
> Fix positioning of column title

- Gruntfile.js
- app/server/templates/services.html
- package.json
We want to see how many people download the Transaction Explorer CSV data. See https://trello.com/c/PsUMu5iu/12-finding-out-how-many-use-the-csv-download
Note it was necessary to upgrade govuk_frontend_toolkit package in order to make use of download-link-tracker.js. The use of this also necessitates the pulling in of JQuery into the Services page.
> Track download of Transactions Explorer CSV data

- app/appBuilder.js
Old static files are being used on deploy, causing page styling to break. Adding cache control to the serving of static files to remedy this.
> Add cache control for static content

- app/server/templates/dashboard.html
- app/server/templates/homepage.html
- app/server/templates/page-components/get_in_touch.html
- app/server/templates/services.html
- app/server/templates/simple-dashboard-list.html
- app/server/views/dashboard.js
- app/server/views/homepage.js
- app/server/views/services.js
- styles/common/layout.scss
- styles/elements/_layout.scss
- styles/pages/homepage.scss
Remove the Get In Touch banner containing a link to a user survey that was used to determine how  people have been using the Performance Platform.
> Revert survey link

- package.json
Bump the spdy library so that HTTP2 will be used rather than the now deprecated Google SPDY protocol.
> Bump spdy library

- app/server/templates/page-components/navigation.html
Remove link to prototypes page while the data team considers what to do with the prototypes accessible via Performance Platform.
> Remove prototypes link from header navigation

- app/server/mixins/get_dashboard_and_render.js
- spec/server-pure/mixins/spec.get_dashboard_and_render.js
- tests/functional/services.js
Stops a XSS injection described in https://govuk.zendesk.com/agent/tickets/1944831
To reproduce you can use this URL: https://www.gov.uk/performance/central-government-websites?sortby=percentOfTotal(count:sum)"'--!></Title/</Style/</script/</Textarea/</Noscr ipt/</Pre/</Xmp><Svg/Onload=confirm`OPENBUGBOUNTY`>&sortorder=descending&=utm_source=test"
Does not ensure all input to this application is sanitized.
> Sanitize user input

- .travis.yml
- README.md
- jenkins.sh
- package.json
Fixes the build in Jenkins by relying on npm scripts checking node_modules
for the local grunt-cli version
> Use npm scripts instead of global grunt

- .travis.yml
- app/appBuilder.js
- app/page_config.js
- config/config.development.json
- jenkins.sh
- spec/server/spec.page_config.js
This should use the GOVUK_WEBSITE_ROOT environment variable instead which is always set correctly.
> Remove govukHost config value

- jenkins.sh
The `./node_modules/` dependencies need to be refreshed on each build to pull in changes from repos like [Cheapseats](https://github.com/alphagov/cheapseats)
> Remove ./node_modules/ before npm install on CI

- app/server/mixins/templater.js
- package.json
- spec/server-pure/mixins/spec.templater.js
- spec/server/spec.page_config.js
Express will cache the result of a call to render() but prior to this
we make a call to `fs.readFileSync` for the mustache or underscore template source.
This means a lot of IO as the static template source is never cached.
This commit adds the memory-cache node module, as this exposes the cache anywhere in the app.
The cached templates are keyed by path. No expiry time was added but this
is possible as a third arg to `cache.put()` if necessary.
Response to a problem found on 2ndline where Spotlight was pinned at 100% CPU and logging the error:
```
Error: EMFILE, too many open files '/.../app/server/templates/module.html'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at module.exports.loadTemplate (/.../app/server/mixins/templater.js:19:23)
```
> Cache template sources

- app/server/templates/homepage.html
Changed subheading copy to "See how many people are using GOV.UK content"
> Fix Web traffic dashboards subheading

- config/config.production.json
- config/config.staging.json
- Local asset path
- Backdrop on GOV.UK staging, not preview
- Stagecraft on PaaS
> Update settings for PaaS

- .travis.yml
- config/config.production.json
- config/config.staging.json
- Correct domain setting for GOV UK (staging
- Change domain setting for Stagecraft on PaaS (Stagecraft domain has been changed to make it consistent with other Performance Platform apps deployed to PaaS)
> Update PaaS settings

- app/appBuilder.js
- config/config.development.json
- config/config.production.json
- config/config.staging.json
Replaces the hard-coded asset path to use the one that is configured.
Even though the config specified /spotlight/ the router enforced the
use of that path making sure config changes had little effect.
Changed config to serve assets through /performance/assets/ to make prod
configuration easier.
> Fixes the path used for asset delivery

- app/client/views/json-summary.js
- app/client/views/module.js
Resolves [this issue](https://github.com/alphagov/spotlight/issues/1048) by waiting until a collection has been returned before trying to manipulate it.
> Wait for collection to exist before building tab interface

- app/client/views/json-summary.js
- spec/client/views/spec.json-summary.js
The previous code was:
1. removing the `<li>` element and replacing it with `<a>` elements
2. adding more `<a>` elements without removing the past ones
This meant that on some pages, where it was possible to filter data in the visualisation, modifying the filters would result in a bunch of links being appended one after another without cleaning up the previous links.
(for example)[https://www.gov.uk/performance/check-driving-information/volumetrics]
This new behaviour works as intended, the code is simpler and the tests are useful.
> Fix link updating behaviour

- README.md
This isn't an overhaul that fixes everything that's out of date in the README, but it does rectify several of the things that I have been working on directly. 
README now has the correct version of npm, description of jasmine tests is fixed, and links to the no-longer-relevant govuk VM have been removed.
> More relevant README

- config/config.staging.json
Tells spotlight to look at the new backdrop hosted in the staging
environment.
> Point at the new backdrop URL

- Gruntfile.js
Updated a bunch of npm libraries in cheapseats to get the tests running again on travis.
A side-effect of this is that we can't use the mocha `spec-retry` reporter.
Wasn't helping us anyway, so good riddance.
> Removed `spec-retry` reporter from cheapseats

- package.json
Due to travis caching the old cheapseats version, there isn't a reliable way of guaranteeing that downstream changes are being pulled into the tests. 
This will make it explicit which version of cheapseats we are using for our tests.
> Pin a version of cheapseats

- app/client/views/json-summary.js
- app/server/templates/module.html
- app/server/views/module.js
- spec/client/views/spec.json-summary.js
- spec/server-pure/views/spec.module.js
Pretty straightforward change. There used to be a JSON link and a CSV link, but now we just have the JSON one. It's still possible to get the original CSV response back if you use the JSON url and then change the query parameter. More detail in the actual commit, which I will include below for completeness.
```
Some of our CSVs are having formatting issues, which leaves us with
several options:
1. fix the formatting issue through backdrop
2. fix the formatting issue by returning CSVs in spotlight
3. remove the CSV links
4. do nothing -- leave everything as it is
We decided that (1) doesn't really solve the problem and that (2)
would be too hard for something we don't really know if people
care about at all.
Going with (3) until we have a compelling reason not to.
//
Note that it is still …
```
> Stop showing CSV links on individual graph pages

- request-lifecycle.md
The genesis of this is that I've spent a bunch of time tracing
through what to me is a labyrinthine application structure.
I can intellectually appreciate that spotlight has a cool,
avant-garde application design or something but, on a practical
level, the thing is hella complicated and all the super smart
people who designed it have left.
Hopefully this is more helpful than the very high level overview
that currently exists in the /docs folder.
//
Notes for @rossjones:
- it's probably more helpful reading this as an interpreted markdown file 👉  like [here](https://github.com/alphagov/spotlight/blob/write-about-requests/request-lifecycle.md)
- there are a _lot_ of links to the code, but that's because when I wrote it without links it felt like it was super confusing
- I've linked to the …
> Add documentation about how spotlight handles requests

- app/appBuilder.js
- package.json
As we are getting lots of impolite requests from specific user agents
(yes, I'm looking at you Pcore-HTTP) we should rate-limit them to
something more reasonable than 30 r/s.
This may not solve the problem (they could change user-agent) but
the same problems with identifying requests exists using other things
such as IP.
We __could__ also rate-limit everyone, but that seems like it might
be wasteful of server resources.
> Rate limits specific user agents

- Gruntfile.js
- package-lock.json
- package.json
Also completes the de-activation of the cheapseats tests so they don't
run when you run ```npm test```
> Update jquery to version 3.0.0

- package.json
This is what happens with the old version:
```Downloaded app package (113.9M)
-----> Nodejs Buildpack version 1.6.22
-----> Installing binaries
engines.node (package.json): 6.12.2
engines.npm (package.json): unspecified (use default)
**ERROR** Unable to install node: no match found for 6.12.2 in [9.9.0 8.10.0 6.13.1 4.8.7 8.11.1 6.14.1 4.9.1 9.11.1]
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
```
> Update to nearest Node version supported by PaaS

- app/extensions/views/table_fallback.js
This stops the app crashing if there's no data to display in the fallback (no-js) tables.
Next, we need to fix the broken layout that is shown in that case, but this will stop the app crashing for now.
> don't crash if there's no data to put in the table

- manifest.production.yml
- manifest.staging.yml
The manifests for spotlight set one name for the app, but
etc/deploy.sh overrides this to a different name.
This is confusing and has left us with multiple copies of spotlight
running, bound to the same route.
To avoid this footgun in future, I think we should have the manifests
use the actual app name that we actually deploy.  I hope this is not a
controversial opinion.
> make manifests match reality

- manifest.production.yml
- manifest.staging.yml
while in maintainance we do not want a public route available to the
application... this comments out the routes and sets `no-route: true`
> disable public route

- manifest.production.yml
- manifest.staging.yml
use `buildpack` over `buildpacks` since blue-green plugin does not
understand the new manifest syntax.
> return to old-style buildpacks

- Gruntfile.js
- app/server/templates/page-components/deprecation_message.html
- app/server/templates/page-components/govuk_template.html
- app/server/views/govuk.js
- manifest.sandbox.yml
- styles/common/raw.scss
Add banner to local copy of govuk_template and prevent its replacement with the npm module version by grunt during build tasks.
> Add banner with deprecation message
